# Step 1: Import all necessary libraries

In [39]:
# Libraries
import pandas as pd
from traffic.data import aircraft
import numpy as np
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

## Step 2: Import existing bottleneck features

In [40]:
helper_bottleneck_features = pd.read_parquet('data/processed/helper_bottleneck_features.parquet')

In [41]:
helper_bottleneck_features.head()

,flight_id,taxi_start,taxi_end,pushback,sum_p10_hist_seg_time,sum_median_hist_seg_time,sum_p90_hist_seg_time,sum_seg_length_m,n_intersections_passed,TO_runway_28,TO_runway_32,TO_runway_16,TO_runway_10,TO_runway_34
0,GSW6KP_4832,2024-12-01 04:44:54+00:00,2024-12-01 04:58:20+00:00,1,NaN,NaN,NaN,711.4,4,0,1,0,0,0
1,EDW200E_4558,2024-12-01 04:58:35+00:00,2024-12-01 05:07:58+00:00,1,NaN,NaN,NaN,1190.3,7,0,1,0,0,0
2,EDW120_4456,2024-12-01 05:18:50+00:00,2024-12-01 05:25:38+00:00,1,NaN,NaN,NaN,740.8,4,0,1,0,0,0
3,EDW15T_4539,2024-12-01 05:31:07+00:00,2024-12-01 05:35:22+00:00,1,NaN,NaN,NaN,1092.5,7,0,1,0,0,0
4,EDW212R_4430,2024-12-01 05:34:06+00:00,2024-12-01 05:46:14+00:00,1,NaN,NaN,NaN,1911.9,11,0,1,0,0,0

## Step 3: Import processed trajectories

In [42]:
trajs_processed = pd.read_parquet('data/processed/trajs_processed.parquet')

In [43]:
trajs_processed.head()

,timestamp,icao24,latitude,longitude,groundspeed,track,vertical_rate,callsign,onground,alert,spi,squawk,altitude,geoaltitude,lastcontact,serials,hour,flight_id,track_unwrapped,cumdist,compute_gs,compute_track,registration,typecode,cut_runway,x,y,groundspeed_xy,track_xy,latitude_kalman,longitude_kalman,groundspeed_kalman,track_kalman,pushback
0,2024-12-03 19:27:23+00:00,501e43,47.454506,8.572392,<NA>,NaN,<NA>,9AJIM,True,False,False,1000,1200.0,<NA>,1733254042.608,[-1408231728],2024-12-03 19:00:00+00:00,9AJIM_8350,NaN,NaN,6.656234,281.121521,9A-JIM,C525,28,1835.107443,-394.409784,10.289896,288.756018,47.454498,8.572272,5.635465,298.075857,0
1,2024-12-03 19:27:24+00:00,501e43,47.454525,8.572311,<NA>,NaN,<NA>,9AJIM,True,False,False,1000,1200.0,<NA>,1733254043.929,[-1408231728],2024-12-03 19:00:00+00:00,9AJIM_8350,NaN,NaN,6.656234,327.148395,9A-JIM,C525,28,1829.065901,-392.298275,9.573292,288.535804,47.454504,8.572235,5.830707,303.050765,0
2,2024-12-03 19:27:25+00:00,501e43,47.454537,8.572259,<NA>,NaN,<NA>,9AJIM,True,False,False,1000,1200.0,<NA>,1733254043.929,[-1408231728],2024-12-03 19:00:00+00:00,9AJIM_8350,NaN,NaN,6.656234,327.148395,9A-JIM,C525,28,1825.082500,-391.005600,8.543856,295.514329,47.454516,8.572201,6.047056,307.521679,0
3,2024-12-03 19:27:26+00:00,501e43,47.454548,8.572206,<NA>,NaN,<NA>,9AJIM,True,False,False,1000,1200.0,<NA>,1733254045.899,[-1408231728],2024-12-03 19:00:00+00:00,9AJIM_8350,NaN,NaN,6.656234,327.148395,9A-JIM,C525,28,1821.099101,-389.712922,6.975231,305.511766,47.454536,8.572171,6.373721,315.379196,0
4,2024-12-03 19:27:27+00:00,501e43,47.454574,8.572181,<NA>,NaN,<NA>,9AJIM,True,False,False,1000,1200.0,<NA>,1733254045.899,[-1408231728],2024-12-03 19:00:00+00:00,9AJIM_8350,NaN,NaN,6.656234,327.148395,9A-JIM,C525,28,1819.240662,-386.836846,6.694868,316.065216,47.454562,8.572144,6.676477,321.610645,0

# Step 4: Import processed meteorological data

In [44]:
meteo_processed = pd.read_parquet('data/processed/meteo_processed.parquet')

## Step 5: Feature Engineering

In the following steps, additional features based on the processed trajectories are being created and then merged with the existing bottleneck features.

### Step 5.1: Operational Features

First, we create a features dataframe and define the target variable (taxi out time) for each flight_id.

In [45]:
features_df = helper_bottleneck_features[
    ["flight_id", "taxi_start", "taxi_end"]
].copy()

features_df["taxi_time_s"] = (
    features_df["taxi_end"] - features_df["taxi_start"]
).dt.total_seconds()

Before defining a filtering threshold, the distribution of taxi-out times is inspected using summary statistics and lower quantiles to understand the realistic range of values.

In [46]:
def inspect_taxi_time_distribution(features_df):

    print("Summary statistics:")
    print(features_df["taxi_time_s"].describe())

    print("\nLower quantiles:")
    print(
        features_df["taxi_time_s"].quantile(
            [0.01, 0.02, 0.05, 0.10]
        )
    )


inspect_taxi_time_distribution(features_df)

Summary statistics:
count    6.227200e+04
mean     1.675239e+04
std      4.092909e+05
min      3.000000e+00
25%      3.770000e+02
50%      5.620000e+02
75%      7.430000e+02
max      2.091277e+07
Name: taxi_time_s, dtype: float64

Lower quantiles:
0.01     41.0
0.02     78.0
0.05    134.0
0.10    196.0
Name: taxi_time_s, dtype: float64

A configurable minimum taxi-out time parameter is defined to allow flexible adjustment of the filtering threshold as the dataset grows or data characteristics change.


 <font color='red'> CHANGE THE PARAMETER IN THE CELL BELOW: </font>

In [47]:
MIN_TAXI_TIME_S = 60

Flights with taxi-out times below the defined minimum threshold are excluded from further analysis to remove incomplete or operationally implausible trajectories.

In [48]:
features_df = features_df[
    features_df["taxi_time_s"] >= MIN_TAXI_TIME_S
]

In [50]:
overnight_flights = features_df[
    features_df["taxi_start"].dt.date != features_df["taxi_end"].dt.date
]

overnight_flights[[
    "flight_id",
    "taxi_start",
    "taxi_end",
    "taxi_time_s"
]].sort_values("taxi_start")

,flight_id,taxi_start,taxi_end,taxi_time_s
2035,BAW719X_1498,2024-12-15 19:10:42+00:00,2025-02-20 18:19:02+00:00,5785700.0
2051,BAW707_1518,2024-12-15 20:14:29+00:00,2025-03-13 20:13:13+00:00,7603124.0
3957,SWR46M_8272,2024-12-29 20:11:53+00:00,2025-01-31 20:19:49+00:00,2851676.0
7012,SWR458E_3847,2025-01-21 11:17:31+00:00,2025-03-10 11:52:10+00:00,4149279.0
11237,BYD091_081,2025-02-21 20:17:54+00:00,2025-03-14 20:26:14+00:00,1814900.0
16977,IBE06DA_252,2025-04-02 17:39:54+00:00,2025-06-12 18:36:04+00:00,6137770.0
17289,DLH7C_1167,2025-04-04 18:06:48+00:00,2025-09-08 18:19:29+00:00,13565561.0
17678,IBE06SV_406,2025-04-07 05:20:29+00:00,2025-04-25 05:45:50+00:00,1556721.0
17796,CFG4310_975,2025-04-07 16:23:20+00:00,2025-05-04 16:10:47+00:00,2332047.0
17928,SWR5GM_4129,2025-04-08 15:23:08+00:00,2025-04-27 16:11:11+00:00,1644483.0
18108,VLG4CT_370,2025-04-09 19:42:48+00:00,2025-09-06 13:47:38+00:00,12938690.0
18237,BTI8GC_9833,2025-04-10 17:11:45+00:00,2025-05-01 17:37:41+00:00,1815956.0
18313,AUA552S_1976,2025-04-11 08:36:42+00:00,2025-10-13 09:09:14+00:00,15985952.0
18427,VLG4CT_352,2025-04-11 20:18:16+00:00,2025-08-13 20:18:23+00:00,10713607.0
18496,SWR238_4884,2025-04-12 10:15:29+00:00,2025-05-26 10:54:22+00:00,3803933.0
18529,AFR77GN_459,2025-04-12 14:04:20+00:00,2025-05-22 12:55:10+00:00,3451850.0
18534,QTR37N_128,2025-04-12 15:02:26+00:00,2025-10-22 14:51:41+00:00,16674555.0
18537,GSW630_5717,2025-04-12 15:08:04+00:00,2025-04-24 16:35:47+00:00,1042063.0
18585,EDW402_3661,2025-04-13 04:48:53+00:00,2025-08-22 04:22:58+00:00,11316845.0
18607,QTR67U_112,2025-04-13 07:49:36+00:00,2025-09-07 09:51:28+00:00,12708112.0
18667,IBE06GP_399,2025-04-13 12:43:03+00:00,2025-05-05 13:12:23+00:00,1902560.0
18698,DLH8C_1120,2025-04-13 16:11:36+00:00,2025-10-10 16:43:22+00:00,15553906.0
18713,MSC2921_027,2025-04-13 18:08:58+00:00,2025-08-17 17:44:17+00:00,10884919.0
18874,AFR52WA_581,2025-04-14 17:34:20+00:00,2025-06-29 18:07:36+00:00,6568396.0
19007,QTR37N_094,2025-04-15 14:36:38+00:00,2025-08-08 14:55:22+00:00,9937124.0
19090,SWR8MB_4328,2025-04-16 07:16:21+00:00,2025-10-24 06:50:30+00:00,16500849.0
19092,QTR67U_102,2025-04-16 07:37:56+00:00,2025-06-16 07:53:30+00:00,5271334.0
19217,CFG4310_896,2025-04-16 16:11:48+00:00,2025-04-23 16:15:52+00:00,605044.0
19230,AFR52WA_577,2025-04-16 17:32:20+00:00,2025-06-18 17:57:13+00:00,5444693.0
19247,EJU87HP_1859,2025-04-16 19:58:35+00:00,2025-04-24 20:51:11+00:00,694356.0
19320,AFR39LA_502,2025-04-17 11:15:17+00:00,2025-06-22 13:11:13+00:00,5709356.0
19382,SWR854_4615,2025-04-17 16:46:31+00:00,2025-05-15 16:46:31+00:00,2419200.0
19437,SWR915W_3942,2025-04-18 05:33:06+00:00,2025-06-26 05:54:19+00:00,5962873.0
19490,IBE06AV_249,2025-04-18 10:07:12+00:00,2025-05-11 10:00:33+00:00,1986801.0
19544,CFG4310_903,2025-04-18 15:54:36+00:00,2025-04-22 16:16:42+00:00,346926.0
19565,ETH737_079,2025-04-18 18:54:59+00:00,2025-08-20 19:32:04+00:00,10715825.0
19577,EJU87HP_1860,2025-04-18 19:40:48+00:00,2025-04-25 20:23:02+00:00,607334.0
19586,SWR5BW_4420,2025-04-18 20:19:37+00:00,2025-08-06 20:11:17+00:00,9503500.0
19611,SWR4HY_4916,2025-04-19 06:22:03+00:00,2025-08-11 05:35:48+00:00,9846825.0
19637,SWR4AH_4369,2025-04-19 09:03:29+00:00,2025-09-28 11:22:02+00:00,14005113.0
19668,RSX8522_029,2025-04-19 12:08:36+00:00,2025-06-28 11:59:38+00:00,6047462.0
19689,SWR757W_5060,2025-04-19 15:06:33+00:00,2025-10-11 15:37:20+00:00,15121847.0
19822,SWR2BY_4409,2025-04-20 10:54:42+00:00,2025-08-06 11:38:08+00:00,9333806.0
19844,SWR2EG_3910,2025-04-20 13:34:10+00:00,2025-04-29 13:45:51+00:00,778301.0
20001,QTR37N_097,2025-04-21 14:28:03+00:00,2025-05-23 14:50:42+00:00,2766159.0
20139,SWR3WL_3916,2025-04-22 11:17:17+00:00,2025-05-15 11:56:04+00:00,1989527.0
20161,QTR37N_093,2025-04-22 14:37:26+00:00,2025-08-24 15:03:59+00:00,10715193.0
20187,AFR52WA_539,2025-04-22 17:26:39+00:00,2025-06-08 17:43:24+00:00,4061805.0
20282,MSC2923_026,2025-04-23 12:16:23+00:00,2025-07-19 18:25:32+00:00,7538949.0
20457,CFE12B_1676,2025-04-24 12:53:32+00:00,2025-08-15 12:29:55+00:00,9761783.0
20551,SWR16F_5249,2025-04-25 08:01:48+00:00,2025-08-21 08:28:47+00:00,10196819.0
20606,SWR2EG_3911,2025-04-25 13:41:31+00:00,2025-05-03 13:41:50+00:00,691219.0
20643,SWR736_4603,2025-04-25 18:51:24+00:00,2025-10-25 18:44:32+00:00,15810788.0
20651,SWR558F_3921,2025-04-25 19:42:49+00:00,2025-05-27 19:46:07+00:00,2764998.0
20667,EDW284_5415,2025-04-26 04:09:50+00:00,2025-05-02 04:55:33+00:00,521143.0
20743,SWR5EC_5964,2025-04-26 10:19:41+00:00,2025-04-29 10:06:08+00:00,258387.0
21056,SWR101X_4280,2025-04-28 15:53:35+00:00,2025-09-01 16:12:41+00:00,10887546.0
21216,AFR52WA_565,2025-04-29 17:22:49+00:00,2025-09-05 17:34:51+00:00,11146322.0
21305,IBE06AV_247,2025-04-30 10:07:32+00:00,2025-07-13 10:15:52+00:00,6394100.0
21311,SWR242_5556,2025-04-30 10:48:47+00:00,2025-07-27 11:32:32+00:00,7605825.0
21314,SWR2BY_4383,2025-04-30 11:00:01+00:00,2025-12-28 12:06:10+00:00,20912769.0
21363,SWR7WA_4929,2025-04-30 16:01:53+00:00,2025-10-31 16:46:33+00:00,15900280.0
21369,SWR9AA_3610,2025-04-30 17:08:03+00:00,2025-08-12 17:27:16+00:00,8986753.0
21418,CFG4312_915,2025-05-01 06:08:12+00:00,2025-05-27 06:13:52+00:00,2246740.0
21452,IBE06AV_230,2025-05-01 09:40:01+00:00,2025-08-25 10:29:36+00:00,10025375.0
21581,EJU31KA_2013,2025-05-02 07:59:02+00:00,2025-08-12 07:50:38+00:00,8812296.0
21811,AEA12WM_270,2025-05-03 16:36:52+00:00,2025-09-15 17:04:35+00:00,11665663.0
21874,SWR80_5553,2025-05-04 08:00:27+00:00,2025-09-20 08:17:58+00:00,12010651.0
21892,AEA44NY_298,2025-05-04 09:11:21+00:00,2025-06-16 09:24:37+00:00,3715996.0
21899,IBE06AV_275,2025-05-04 09:59:37+00:00,2025-07-08 12:24:10+00:00,5624673.0
21919,SWR86_5533,2025-05-04 11:14:25+00:00,2025-05-25 11:06:41+00:00,1813936.0
21990,SWR9KF_10453,2025-05-04 16:38:05+00:00,2025-08-23 16:22:23+00:00,9589458.0
22022,SWR1338_10297,2025-05-04 19:57:35+00:00,2025-08-21 20:52:45+00:00,9420910.0
22033,SWR1886_10404,2025-05-04 20:51:08+00:00,2025-10-03 20:12:35+00:00,13130487.0
22076,SWR5ZM_10578,2025-05-05 07:43:23+00:00,2025-09-23 08:02:30+00:00,12183547.0
22078,SWR36K_5228,2025-05-05 07:50:32+00:00,2025-11-11 09:53:47+00:00,16423395.0
22079,SWR154_5538,2025-05-05 07:56:33+00:00,2025-08-31 07:59:17+00:00,10195364.0
22087,PGT996H_9375,2025-05-05 08:52:13+00:00,2025-09-08 09:07:10+00:00,10887297.0
22144,THY7ZV_9360,2025-05-05 13:12:04+00:00,2025-07-16 13:30:15+00:00,6221891.0
22159,PGT2TF_9409,2025-05-05 14:18:02+00:00,2025-09-21 14:11:57+00:00,12009235.0
22176,SWR9KF_3871,2025-05-05 15:53:25+00:00,2025-10-22 15:40:19+00:00,14687214.0
22217,SWR24C_4911,2025-05-05 19:00:46+00:00,2025-05-16 19:07:49+00:00,950823.0
22256,THY3SP_9322,2025-05-06 05:44:33+00:00,2025-09-24 05:56:10+00:00,12183097.0
22258,SWR3EZ_4564,2025-05-06 06:05:56+00:00,2025-10-08 06:18:58+00:00,13392782.0
22309,SWR72_5515,2025-05-06 10:58:08+00:00,2025-07-17 11:37:41+00:00,6223173.0
22382,EWG7LL_705,2025-05-06 18:24:52+00:00,2025-10-22 20:19:15+00:00,14608463.0
22388,EJU31FK_2035,2025-05-06 19:21:40+00:00,2025-06-16 19:29:02+00:00,3542842.0
22479,SWR105Z_4171,2025-05-07 10:46:46+00:00,2025-08-18 11:11:01+00:00,8900655.0
22502,MSC2923_021,2025-05-07 12:03:45+00:00,2025-11-01 17:43:08+00:00,15399563.0
22559,KLM88B_2680,2025-05-07 17:47:58+00:00,2025-08-05 17:29:15+00:00,7774877.0
22560,IBE06DA_247,2025-05-07 17:48:16+00:00,2025-07-23 18:25:11+00:00,6655015.0
22614,SWR2HD_3468,2025-05-08 06:26:52+00:00,2025-10-07 06:18:24+00:00,13132292.0
22645,CAZ401_3565,2025-05-08 10:06:03+00:00,2025-05-25 05:35:45+00:00,1452582.0
22647,IBE06AV_276,2025-05-08 10:15:09+00:00,2025-09-30 10:21:43+00:00,12528394.0
22691,UAE87Q_10848,2025-05-08 13:42:46+00:00,2025-08-16 13:57:27+00:00,8640881.0
22736,CFE8768_1699,2025-05-08 17:36:31+00:00,2025-06-08 18:48:34+00:00,2682723.0
22762,EDW130J_5823,2025-05-09 03:54:57+00:00,2025-08-29 04:40:27+00:00,9679530.0
22803,UAL12_10961,2025-05-09 07:48:15+00:00,2025-08-11 08:26:18+00:00,8123883.0
22865,THA971_10829,2025-05-09 11:35:35+00:00,2025-08-15 12:04:04+00:00,8468909.0
22933,SWR5MT_10388,2025-05-09 17:04:32+00:00,2025-06-18 16:14:17+00:00,3452985.0
22973,VLG4CT_336,2025-05-09 20:09:38+00:00,2025-06-07 14:10:12+00:00,2484034.0
23003,SAZ71_6685,2025-05-10 05:53:06+00:00,2025-06-09 09:14:01+00:00,2604055.0
23018,SWR16F_5526,2025-05-10 08:11:32+00:00,2025-06-20 08:37:09+00:00,3543937.0
23034,PGT4EA_9408,2025-05-10 09:56:49+00:00,2025-07-04 10:00:57+00:00,4752248.0
23046,SWR74D_4536,2025-05-10 10:56:52+00:00,2025-06-07 11:26:21+00:00,2420969.0
23064,SWR40_5964,2025-05-10 11:37:07+00:00,2025-06-17 12:51:48+00:00,3287681.0
23077,UAE87Q_10844,2025-05-10 13:24:18+00:00,2025-10-03 13:46:21+00:00,12615723.0
23078,EDW288G_3577,2025-05-10 13:30:51+00:00,2025-06-14 15:09:13+00:00,3029902.0
23111,EDW49Q_3673,2025-05-10 15:56:46+00:00,2025-05-26 15:02:35+00:00,1379149.0
23257,QTR37N_106,2025-05-11 14:37:47+00:00,2025-08-03 14:53:13+00:00,7258526.0
23270,CFG4310_1028,2025-05-11 16:06:16+00:00,2025-05-23 16:17:47+00:00,1037491.0
23367,SWR4AH_4689,2025-05-12 10:10:03+00:00,2025-06-02 10:39:27+00:00,1816164.0
23481,EDW402_3769,2025-05-13 04:37:30+00:00,2025-08-03 05:17:03+00:00,7087173.0
23508,QTR67U_095,2025-05-13 07:31:33+00:00,2025-08-27 08:08:40+00:00,9160627.0
23536,SWR11P_3484,2025-05-13 11:07:03+00:00,2025-11-25 11:54:43+00:00,16937260.0
23705,KLM38T_2781,2025-05-14 15:52:58+00:00,2025-10-19 16:00:20+00:00,13651642.0
23739,VLG4CT_317,2025-05-14 19:47:38+00:00,2025-06-03 20:13:21+00:00,1729543.0
23919,SWR44X_4151,2025-05-15 21:01:52+00:00,2025-07-21 20:01:43+00:00,5785191.0
24007,AUA5ZC_2389,2025-05-16 12:01:24+00:00,2025-09-06 12:12:53+00:00,9763889.0
24008,SWR3WL_5432,2025-05-16 12:06:13+00:00,2025-06-01 12:32:05+00:00,1383952.0
24150,SWR4PX_4981,2025-05-17 10:20:42+00:00,2025-06-14 10:56:10+00:00,2421328.0
24397,SWR736_5166,2025-05-18 18:33:22+00:00,2025-09-19 18:51:19+00:00,10714677.0
24516,AUA5ZC_2352,2025-05-19 11:32:00+00:00,2025-07-09 12:31:14+00:00,4409954.0
24568,IBE06DA_255,2025-05-19 18:06:35+00:00,2025-07-26 18:04:37+00:00,5875082.0
24635,AFR39LA_577,2025-05-20 09:41:02+00:00,2025-08-21 09:32:56+00:00,8034714.0
24647,SWR8AQ_3510,2025-05-20 10:47:36+00:00,2025-07-14 11:36:21+00:00,4754925.0
24714,AUA566_2359,2025-05-20 18:25:42+00:00,2025-09-27 18:57:05+00:00,11233883.0
24813,SWR5PF_3767,2025-05-21 11:27:49+00:00,2025-08-22 11:16:21+00:00,8034512.0
24844,QTR37N_101,2025-05-21 14:39:29+00:00,2025-07-12 14:49:51+00:00,4493422.0
27452,EWG97MT_688,2025-06-04 19:09:12+00:00,2025-08-03 18:46:28+00:00,5182636.0
27579,EDW346M_5706,2025-06-05 12:19:40+00:00,2025-08-29 04:57:23+00:00,7317463.0
28262,GPX601_2450,2025-06-08 18:45:47+00:00,2025-10-21 18:40:03+00:00,11663656.0
31556,SWR1958_3985,2025-06-27 14:21:42+00:00,2025-08-10 14:15:00+00:00,3801198.0
32731,SWR43C_6395,2025-07-04 10:40:21+00:00,2025-09-09 11:11:19+00:00,5790658.0
32763,UAE87Q_11129,2025-07-04 13:29:50+00:00,2025-09-06 13:52:20+00:00,5530950.0
36445,SWR317K_3562,2025-07-24 15:56:49+00:00,2025-08-15 15:24:00+00:00,1898831.0
42835,SWR4TH_3930,2025-08-30 19:10:10+00:00,2025-10-18 20:05:11+00:00,4236901.0
42974,BTI8GC_10650,2025-08-31 17:25:33+00:00,2025-09-25 17:25:15+00:00,2159982.0
43273,SWR3CX_4873,2025-09-02 15:06:01+00:00,2025-10-25 16:29:03+00:00,4584182.0
43838,EDW438_5701,2025-09-05 17:18:46+00:00,2025-09-14 17:00:30+00:00,776504.0

Adding aircraft typecode as a feature and setting datatype as "category"

In [ ]:
typecode_lookup = (
    trajs_processed[["flight_id", "typecode"]]
    .dropna(subset=["typecode"])
    .drop_duplicates()
)

features_df = features_df.merge(
    typecode_lookup,
    on="flight_id",
    how="left"
)

features_df["typecode"] = features_df["typecode"].astype("category")

The queue size feature is calculated within a rolling one-hour lookback window. For each flight, only aircraft that started taxiing within the previous hour and were still taxiing at the current flight's taxi_start time are counted. This keeps the feature operationally realistic, prediction-safe, and computationally scalable for larger datasets.

In [ ]:
WINDOW = pd.Timedelta(hours=1)

features_df = features_df.sort_values("taxi_start")

starts = features_df["taxi_start"]
ends = features_df["taxi_end"]

queue_size_last_hour = []

for i, t in enumerate(starts):
    n_active = (
        (starts >= t - WINDOW)
        & (starts < t)
        & (ends > t)
    ).sum()

    queue_size_last_hour.append(n_active)

features_df["queue_size"] = queue_size_last_hour

Implementing the average taxi out time of the past 6 hours as a feature

In [ ]:
WINDOW = pd.Timedelta(hours=6)

features_df = features_df.sort_values("taxi_start")

starts = features_df["taxi_start"]
ends = features_df["taxi_end"]
taxi_times = features_df["taxi_time_s"]

avg_taxi_out_6h = []

for i, t in enumerate(starts):

    mask = (
        (ends >= t - WINDOW)
        & (ends < t)
    )

    if mask.any():
        avg = taxi_times[mask].mean()
    else:
        avg = None

    avg_taxi_out_6h.append(avg)

features_df["avg_taxi_out_time_6h"] = avg_taxi_out_6h

Implementing the average taxi out time of the past hour as a feature.

In [ ]:
WINDOW = pd.Timedelta(hours=1)

features_df = features_df.sort_values("taxi_start")

starts = features_df["taxi_start"]
ends = features_df["taxi_end"]
taxi_times = features_df["taxi_time_s"]

avg_taxi_out_1h = []

for i, t in enumerate(starts):

    mask = (
        (ends >= t - WINDOW)
        & (ends < t)
    )

    if mask.any():
        avg = taxi_times[mask].mean()
    else:
        avg = None

    avg_taxi_out_1h.append(avg)

features_df["avg_taxi_out_time_1h"] = avg_taxi_out_1h

Implementing the average taxi out time of the past 15 minutes as feature.

In [ ]:
WINDOW = pd.Timedelta(hours=0.25)

features_df = features_df.sort_values("taxi_start")

starts = features_df["taxi_start"]
ends = features_df["taxi_end"]
taxi_times = features_df["taxi_time_s"]

avg_taxi_out_15min = []

for i, t in enumerate(starts):

    mask = (
        (ends >= t - WINDOW)
        & (ends < t)
    )

    if mask.any():
        avg = taxi_times[mask].mean()
    else:
        avg = None

    avg_taxi_out_15min.append(avg)

features_df["avg_taxi_out_time_15min"] = avg_taxi_out_15min

Implementing bottleneck features

In [ ]:
cols_to_merge = [
    "flight_id",
    "n_intersections_passed",
    "sum_seg_length_m",
    "sum_p10_hist_seg_time",
    "sum_median_hist_seg_time",
    "sum_p90_hist_seg_time",
    "TO_runway_28",
    "TO_runway_32",
    "TO_runway_16",
    "TO_runway_10",
    "TO_runway_34",
    "pushback",
]

features_df = features_df.merge(
    helper_bottleneck_features[cols_to_merge],
    on="flight_id",
    how="left",
)

### Step 5.2 Temporal Features

Defining a function for cyclic encoding

In [ ]:
def sin_cos(x,T):
    return np.sin(2 * np.pi * x / T), np.cos(2 * np.pi * x / T)

Splitting up information from the 'taxi_start' column into month, day of week and minute of day

In [ ]:
features_df["month"] = features_df["taxi_start"].dt.month

features_df["day_of_week"] = features_df["taxi_start"].dt.dayofweek
# Monday = 0, Sunday = 6

features_df["minute_of_day"] = (
    features_df["taxi_start"].dt.hour * 60
    + features_df["taxi_start"].dt.minute
)

Encoding month, day of week and minute of day as sin and cos

In [ ]:
features_df["month_sin"], features_df["month_cos"] = sin_cos(
    features_df["month"], 12
)

features_df["day_of_week_sin"], features_df["day_of_week_cos"] = sin_cos(
    features_df["day_of_week"], 7
)

features_df["minute_of_day_sin"], features_df["minute_of_day_cos"] = sin_cos(
    features_df["minute_of_day"], 24 * 60
)

Adding a timestamp to the dataframe. This won't be used as a feautre but it will be used to define folds based on date

### Step 5.3: Meteorological Features

Implementing temperature and spread as  features

In [ ]:
meteo_temp = (
    meteo_processed[
        ["reference_timestamp", "tre200s0", "spread"]
    ]
    .rename(
        columns={
            "tre200s0": "temp_at_taxi_start",
            "spread": "spread_at_taxi_start"
        }
    )
)

features_df = pd.merge_asof(
    features_df.sort_values("taxi_start"),
    meteo_temp.sort_values("reference_timestamp"),
    left_on="taxi_start",
    right_on="reference_timestamp",
    direction="backward"
)

features_df = features_df.drop(columns="reference_timestamp")

In [ ]:
features_df.head(6)

Export features as parquet file

In [ ]:
output_path = "data/processed/features.parquet"
 
# Save dataframe to pkl.
features_df.to_parquet(output_path)
 
print(f"File \"features\" saved to: {output_path}")